<?php

return array(    
    //'products' => 'site/products',
    'cart/zakazinfo' => 'cart/zakazinfo',
    'checkout' => 'site/checkout',
	'zakaz' => 'site/zakaz',
    'decor' => 'site/decor',
    'health' => 'site/health',
    'mobile' => 'site/mobile',
    'admin/exit'=> 'admin/exit',
    'admin/enter'=> 'admin/enter',
    'admin/sectioncomand/([\w]+)'=>'admin/sectionComand/$1',
    'admin/categorycomand/([\w]+)'=>'admin/categoryComand/$1',
	'admin/brendscomand/([\w]+)'=>'admin/brendsComand/$1',
	'admin/colorscomand/([\w]+)'=>'admin/colorsComand/$1',
	'admin/sizescomand/([\w]+)'=>'admin/sizesComand/$1',
    'admin/productcomand/([\w]+)'=>'admin/productComand/$1',
    'admin/getallforproducts' => 'admin/getAllForProducts',
    'admin/section'=>'admin/section',
	'admin/category'=>'admin/category',
	'admin/brends'=>'admin/brends',
	'admin/colorandsize'=>'admin/colorandsize',
    'admin/product'=>'admin/product',
    'admin'  => 'admin/index',
    'category/([0-9]+)/([0-9]+)' => 'category/products/$1/$2',
    'category/([0-9]+)' => 'category/products/$1/1',
    'single/([0-9]+)' => 'single/product/$1',
    'cart/add/([0-9]+)' => 'cart/add/$1',
    'cart/sub/([0-9]+)' => 'cart/sub/$1',
    'cart/clear' => 'cart/clear',
    'cart/info' => 'cart/info',
    
    'error' => 'site/error',
    'contact' => 'site/contact',
    'brends'=> 'site/products',
    'products' => 'site/products',
    '[\w]+' => 'site/error',
    '' => 'site/index'
);
